apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-web-rps
  namespace: demo
spec:
  scaleTargetRef:
    name: demo-web
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 60
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kps-kube-prometheus-stack-prometheus.monitoring.svc:9090
        metricName: demo_web_rps
        query: sum(rate(nginx_ingress_controller_requests{namespace="demo", ingress="demo-web"}[1m]))
        threshold: "50"

